<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>eu.europeana.metis-processing-engine</groupId>
    <artifactId>metis-processing-engine</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>metis-processing-engine-indexing</artifactId>




  <dependencies>
    <dependency>
      <groupId>eu.europeana.metis-processing-engine</groupId>
      <artifactId>flink-node-shared-libs</artifactId>
      <version>${parent.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.flink</groupId>
      <artifactId>flink-streaming-java</artifactId>
      <version>${flink-version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.flink</groupId>
      <artifactId>flink-clients</artifactId>
      <version>${flink-version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>eu.europeana.metis-processing-engine</groupId>
      <artifactId>metis-processing-engine-commons</artifactId>
      <version>${parent.version}</version>
    </dependency>



    <dependency>
      <groupId>eu.europeana.metis</groupId>
      <artifactId>metis-indexing</artifactId>
      <version>${metis.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.maven.surefire</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.security</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-slf4j-impl</artifactId>
        </exclusion>
        <!--Netty used in the indexing job caused memory leaks - MET-6311 moved to shared lib-->
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <!--Mongo client used in the indexing job caused memory leaks - MET-6311,
        so moved the whole morphia and flapdoodle to shared lib-->
        <exclusion>
          <groupId>de.flapdoodle.embed</groupId>
          <artifactId>de.flapdoodle.embed.mongo</artifactId>
        </exclusion>
        <exclusion>
          <groupId>dev.morphia.morphia</groupId>
          <artifactId>morphia-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
<!--    Needed by metis-indexing-->
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>eu.europeana.metis-processing-engine</groupId>
      <artifactId>test-commons</artifactId>
      <version>${parent.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>metis-processing-engine-indexing</finalName>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>make-assembly</id>
            <configuration>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <appendAssemblyId>false</appendAssemblyId>
              <archive>
                <manifest>
                  <mainClass>
                    eu.europeana.processing.indexing.IndexingJob
                  </mainClass>
                </manifest>
              </archive>
            </configuration>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>