kind: Service
apiVersion: v1
metadata:
  name: flink-job-manager-temp
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob-server
      port: 6124
    - name: webui
      port: 8081
  selector:
    job-name: job-name-template-to-replace
