kind: Deployment
apiVersion: apps/v1
metadata:
  name: flink-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: task-manager
  template:
    metadata:
      labels:
        app: flink
        component: task-manager
    spec:
      serviceAccountName: flink-sa
      imagePullSecrets:
        - name: docker-registry-secret
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: task-manager
          livenessProbe:
            tcpSocket:
              port: 6122
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: rpc
              containerPort: 6122
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: flink-log-properties-volume
              mountPath: /opt/flink/conf/log4j-console.properties
              subPath: log4j-console.properties
            - name: flink-config-volume
              mountPath: /opt/flink/conf/config.yaml
              subPath: config.yaml
            - name: log-volume
              mountPath: /opt/flink/log
            - name: dumps
              mountPath: /dumps
            - name: http-jobs
              mountPath: /http-jobs
          terminationMessagePolicy: File
          image: 'registry.paas.psnc.pl/ecloud-poc/flink-oai-job:v1'
          args:
            - taskmanager
      volumes:
        - name: flink-log-properties-volume
          configMap:
            name: log4j-console-properties
            defaultMode: 511
        - name: flink-config-volume
          secret:
            secretName: flink-config-secret-template-to-replace
            defaultMode: 511
        - name: log-volume
          emptyDir: {}
        - name: dumps
          emptyDir: {}
        - name: http-jobs
          persistentVolumeClaim:
            claimName: http-jobs
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600