FROM registry.paas.psnc.pl/ecloud-poc/metis-processing-engine-flink:2.0.0-java21
LABEL maintainer="PSNC"
COPY target/metis-processing-engine-validation.jar /opt/flink/usrlib/metis-processing-engine-validation.jar
